workflows:
  react-native-ios:
    name: Build React Native iOS
    max_build_duration: 60
    environment:
      vars:
        XCODE_WORKSPACE: "ios/YourApp.xcworkspace" 
        XCODE_SCHEME: "YourApp"                     
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "com.yourname.yourapp"
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
      - name: Bundle React Native code
        script: |
          cd ..
          npx react-native bundle --platform ios --entry-file index.js --bundle-output ios/main.jsbundle --assets-dest ios
    artifacts:
      - build/ios/ipa/*.ipa
